using Microsoft.EntityFrameworkCore;
using MRDN68_HFT_2021221.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MRDN68_HFT_2021221.Data
{
    class MovieProgrammeDbContext :DbContext
    {
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }

        public MovieProgrammeDbContext()
        {
            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.
                    UseLazyLoadingProxies().
                    UseSqlServer(@"Data Source = (LocalDB)\MSSQLLocalDB; AttachDbFilename|DataDirectory|\MovieProgramme.mdf; Integrated Security = True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // "The primary key value needs to be specified even if it's usually generated by the database. It will be used to detect data changes between migrations"
            Director tarantino = new Director() { Id = 1, Name = "Quentin Tarantino" };
            Director jackson = new Director() { Id = 2, Name = "Peter Jackson" };
            Director colombus = new Director() { Id = 3, Name = "Chris Colombus" };

            Movie tarantino1 = new Movie() { Id = 1, DirectorId = tarantino.Id, Year = 1994, Name = "Pulp Fiction", Rating = AgeRating.Restricted };
            Movie tarantino2 = new Movie() { Id = 2, DirectorId = tarantino.Id, Year = 2003 ,Name = "Kill Bill 1.", Rating = AgeRating.Restricted };
            Movie jackson1 = new Movie() { Id = 3, DirectorId = jackson.Id, Year = 2003, Name = "Lord of the Rings: The Return of the King", Rating = AgeRating.ParentsStronglyCautioned };
            Movie jackson2 = new Movie() { Id = 4, DirectorId = jackson.Id, Year = 2003, Name = "Lord of the Rings: The two Towers", Rating = AgeRating.ParentsStronglyCautioned };
            Movie colombus1 = new Movie() { Id = 5, DirectorId = colombus.Id, Year = 2001, Name = "Harry Potter and the Philosopher's Stone", Rating = AgeRating.ParentalGuidanceSuggested };
            Movie colombus2 = new Movie() { Id = 6, DirectorId = colombus.Id, Year = 2004, Name = "Harry Potter and the Prisoner of Azkaban" , Rating = AgeRating.ParentalGuidanceSuggested};

            // FLUENT API (lehetne a Brand osztalyban is -> ForeignKey attributum)
            modelBuilder.Entity<Movie>(entity =>
            {
                entity.HasOne(movie => movie.Director)
                    .WithMany(Director => Director.Movies)
                    .HasForeignKey(movie => movie.DirectorId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<Director>().HasData(tarantino, jackson, colombus);
            modelBuilder.Entity<Movie>().HasData(tarantino1, tarantino2, jackson1, jackson2, colombus1, colombus2);
        }

    }
}
